---
title: "Health Analysis"
author: "WAK"
date: "today"
format: 
  html:
    toc: true 
    toc-float: true
    toc-location: left
---

## 

```{r}
#| include: false
#| warning: false
#| echo: false

library(epiDisplay)
library(knitr)
library(pROC)
library(tidyverse)
library(readxl)
library(ggplot2)
library(gmodels)
library(ggbeeswarm)
library(dplyr)
library(ggpubr)
library(psych)
library(lme4)
library(Matrix)
library(lmerTest)
library(irr)
library(lmerTest)
library(emmeans)
library(doBy)       
library(gmodels)    
library(car)           
library(cowplot)       
library(gridGraphics)  
library(multcomp)
library(hms)
library(gt)
```

```{r}
#| include: false
#| echo: false
#| warning: false

enroll <- read_csv('data/enroll with IgG.csv')

clean <- 
 enroll[-c(157:998), ]

clean <-
  clean |> 
  mutate(
    D0Fed2VolRefusemL = as.numeric(D0Fed2VolRefusemL)
  )

stp <- read_csv('data/stptrouw.csv')

```

## Data Exploration

```{r}
#| echo: false
#| warning: false

clean |> 
ggplot(mapping = aes(x = D0Fed2TxGrp, y = BirthWtLbs, color=D0Fed2TxGrp)) +
  theme_classic()+
  geom_boxplot(outlier.shape=NA) +
  geom_jitter() +
  labs(x = "Second Feeding Treatment", 
       y = "Birth Weight (lbs)", 
       title = "Boxplot of Treatment vs. Birth Weight")
```

```{r}
#| echo: false
#| warning: false

clean |> 
ggplot(mapping = aes(x = D0Fed2TxGrp, y = Result8hrgL, color=D0Fed2TxGrp)) +
  theme_classic()+
  geom_boxplot(outlier.shape=NA) +
  geom_jitter() +
  labs(x = "Second Feeding Treatment", 
       y = "Serum IgG at 8 hrs", 
       title = "Treatment vs. IgG at 8 hours")+
  scale_y_continuous(limits = c(0, 60), breaks = seq(0, 60, by = 10))




```

```{r}
#| echo: false
#| warning: false

clean |> 
ggplot(mapping = aes(x = D0Fed2TxGrp, y = Result24hrgL, color=D0Fed2TxGrp)) +
  theme_classic()+
  geom_boxplot(outlier.shape=NA) +
  geom_jitter() +
  labs(x = "Second Feeding Treatment", 
       y = "Serum IgG at 24 hrs", 
       title = "Treatment vs. IgG at 24 hours")+
  scale_y_continuous(limits = c(0, 60), breaks = seq(0, 60, by = 10))
 


```

```{r}
#| echo: false
#| warning: false

clean |> 
ggplot(mapping = aes(x = CalfSizeLgSm, y = Result24hrgL, color=CalfSizeLgSm)) +
  theme_classic()+
  geom_boxplot(outlier.shape=NA) +
  geom_jitter() +
  labs(x = "Calf Size", 
       y = "Serum IgG at 24 hrs", 
       title = "Calf Size vs. IgG at 24 hours")+
  scale_y_continuous(limits = c(0, 60), breaks = seq(0, 60, by = 10))
```

```{r}
#| echo: false
#| warning: false

clean |> 
ggplot(mapping = aes(x = D0Fed2TxGrp, y = DOFed1MinOld, color=D0Fed2TxGrp)) +
  theme_classic()+
  geom_boxplot(outlier.shape=NA) +
  geom_jitter() +
  labs(x = "Second Feeding Treatment", 
       y = "Age at Feeding", 
       title = "Boxplot of Treatment vs. Age at First Feeding(hrs)")
```

```{r}
#| echo: false
#| warning: false

clean |> 
ggplot(mapping = aes(x = D0Fed2TxGrp, y = DOFed2HrsOld, color=D0Fed2TxGrp)) +
  theme_classic()+
  geom_boxplot(outlier.shape=NA) +
  geom_jitter() +
  labs(x = "Second Feeding Treatment", 
       y = "Age at Feeding", 
       title = "Boxplot of Treatment vs. Age at Second Feeding(hrs)")
```

```{r}
#| echo: false
#| warning: false

clean |> 
ggplot(mapping = aes(x = D0Fed2TxGrp, y = DOFed12IntervHrs, color=D0Fed2TxGrp)) +
  theme_classic()+
  geom_boxplot(outlier.shape=NA) +
  geom_jitter() +
  labs(x = "Second Feeding Treatment", 
       y = "Interval between Feedings (hrs)", 
       title = "Boxplot of Treatment vs. Interval between first and second feeding")
```

```{r}
#| echo: false
#| warning: false

#| echo: false
#| warning: false

clean |> 
ggplot(mapping = aes(x = D0Fed2TxGrp, y = D0Fed2VolRefusemL, color=D0Fed2TxGrp)) +
  theme_classic()+
  geom_boxplot(outlier.shape=NA) +
  geom_jitter() +
  labs(x = "Second Feeding Treatment", 
       y = "Refusal (ml)", 
       title = "Boxplot of Treatment vs. refusal at second feeding")


```

```{r}
#| echo: false
#| warning: false

clean |> 
ggplot(mapping = aes(x = D0Fed2TxGrp, y = D1MilkRefusemL, color=D0Fed2TxGrp)) +
  theme_classic()+
  geom_boxplot(outlier.shape=NA) +
  geom_jitter() +
  labs(x = "Second Feeding Treatment", 
       y = "24hr milk refusal", 
       title = "Boxplot of Treatment vs. 24hr milk refusal")
```

```{r}
#| echo: false
#| warning: false

n_group <- 
  clean |> 
  group_by(D0Fed2TxGrp) |> 
  summarize (Count = n())


summary_sex <- 
  clean |> 
  group_by(D0Fed2TxGrp, SexMF) |> 
  summarize(Count = n())


summary_cb <- 
  clean |> 
  group_by(D0Fed2TxGrp, CrossbredYN) |> 
  summarize(Count = n())


summary_size<-
  clean |> 
  group_by(D0Fed2TxGrp, CalfSizeLgSm) |> 
  summarize(Count=n())


sick_<-
  clean |> 
  group_by(D0Fed2TxGrp, FarmDzYN) |> 
  summarize(count=n())



n_group
summary_sex
summary_cb
summary_size
sick_
```

### Histogram of stp for presentation

```{r}
#| echo: false
#| warning: false

stp<-
  stp |> 
  filter (
    STP <= 10)


fpt<- 
  stp |> 
  mutate(
    FPT = case_when(
      STP<= 5.1 ~ 1, 
      STP > 5.1 ~ 0)) |> 
  group_by(FPT) |> 
  count()


stp |> 
ggplot(mapping = aes(x = STP)) +
  theme_classic() +
  geom_histogram(bins =40, fill = "steelblue", color = "black") +
  scale_x_continuous(breaks = seq(0, max(table(stp$STP)), by = 1))+
  labs( 
       y = "Number of Calves", 
       x = "Serum Total Protein (g/dL)",
       title = "STP of calves at Arrival") 
  



```
